name: Release Build & Push to GCP

on:
  push:
    tags:
      - 'v*.*.*'      # e.g. v1.2.3
  workflow_dispatch:

permissions:
  contents: read      # for checkout
  id-token: write     # if you switch to OIDC auth

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION:     ${{ secrets.GCP_REGION }}
  REPO:       ${{ secrets.GCP_ARTIFACT_REPOSITORY }}
  IMAGE:      finovo-ui
  SA_KEY:     ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id:      ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SA_KEY }}
          export_default_credentials: false

      - name: Activate Service Account
        run: |
          echo "${{ env.SA_KEY }}" > "${HOME}/sa-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/sa-key.json"
          gcloud config set project "${{ env.PROJECT_ID }}"

      - name: Enable IAM Credentials API
        run: |
          gcloud services enable iamcredentials.googleapis.com --quiet

      - name: Configure Docker Auth
        run: |
          HOST="${{ env.REGION }}-docker.pkg.dev"
          gcloud auth configure-docker "$HOST" --quiet

      - name: Build & Push Docker Image
        run: |
          HOST="${{ env.REGION }}-docker.pkg.dev"
          SHA_TAG="$HOST/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}
