name: Build & Push Docker Image to GCP Artifact Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read              # for checkout
  id-token: write             # required by google-github-actions/auth@v1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION:     ${{ secrets.GCP_REGION }}              # e.g. europe-west1
      REPO:       ${{ secrets.GCP_ARTIFACT_REPOSITORY }}  # your docker repo name
      IMAGE:      finovo-ui

    steps:
      # 1. Check out your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Authenticate to GCP (generates an OIDC token under the hood)
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # 3. Configure Docker auth for Artifact Registry
      - name: Configure Docker for Artifact Registry
        uses: google-github-actions/artifact-registry-auth@v0
        with:
          location:   ${{ env.REGION }}
          repository: ${{ env.REPO }}

      # 4. Build & push your Docker image
      - name: Build & Push Docker Image
        run: |
          HOST="$REGION-docker.pkg.dev"
          SHA_TAG="$HOST/$PROJECT_ID/$REPO/$IMAGE:${GITHUB_SHA}"
          LATEST_TAG="$HOST/$PROJECT_ID/$REPO/$IMAGE:latest"

          echo "Building $SHA_TAG"
          docker build -t "$SHA_TAG" .

          echo "Pushing $SHA_TAG"
          docker push "$SHA_TAG"

          echo "Tagging and pushing $LATEST_TAG"
          docker tag "$SHA_TAG" "$LATEST_TAG"
          docker push "$LATEST_TAG"
