name: Build & Push Docker Image to GCP Artifact Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4


      # 2. Write the service account JSON key to disk
      - name: Write GCP key file
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > sa.json

      # 3. Install the Cloud SDK so we have `gcloud`
      - name: Install gcloud SDK
        uses: google-github-actions/install-gcloud@v1
        with:
          version: 'latest'


      # 4. Authenticate and set project
      - name: Authenticate to GCP
        run: |
          gcloud auth activate-service-account --key-file=sa.json
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"

      # 5. Obtain an access token and do a Docker login
      - name: Docker login to Artifact Registry
        run: |
          REGION="${{ secrets.GCP_REGION }}-docker.pkg.dev"
          TOKEN=$(gcloud auth print-access-token)
          echo "$TOKEN" | docker login -u oauth2accesstoken --password-stdin "https://$REGION"

      # 6. Build & push your image
      - name: Build & Push Docker Image
        run: |
          # Define variables
          REGISTRY=${{ secrets.GCP_REGION }}-docker.pkg.dev
          PROJECT=${{ secrets.GCP_PROJECT_ID }}
          REPO=${{ secrets.GCP_ARTIFACT_REPOSITORY }}
          IMAGE_NAME=finovo-ui

          # Full image references
          SHA_TAG=$REGISTRY/$PROJECT/$REPO/$IMAGE_NAME:${{ github.sha }}
          LATEST_TAG=$REGISTRY/$PROJECT/$REPO/$IMAGE_NAME:latest

          echo "Building $SHA_TAG"
          docker build -t $SHA_TAG .

          echo "Pushing $SHA_TAG"
          docker push $SHA_TAG

          echo "Tagging and pushing $LATEST_TAG"
          docker tag $SHA_TAG $LATEST_TAG
          docker push $LATEST_TAG
