name: Build & Push Docker Image to GCP Artifact Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 3. Install & authenticate gcloud
      - name: Setup gcloud SDK & authenticate
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true  # makes gcloud auth available to gcloud commands

      # 2. Setup Docker authentication for Artifact Registry
      - name: Configure Docker for Artifact Registry
        uses: google-github-actions/artifact-registry-auth@v1
        with:
          location: ${{ secrets.GCP_REGION }}
          repository: ${{ secrets.GCP_ARTIFACT_REPOSITORY }}
          format: docker

      # 6. Build & push your image
      - name: Build & Push Docker Image
        run: |
          # Define variables
          REGISTRY=${{ secrets.GCP_REGION }}-docker.pkg.dev
          PROJECT=${{ secrets.GCP_PROJECT_ID }}
          REPO=${{ secrets.GCP_ARTIFACT_REPOSITORY }}
          IMAGE_NAME=finovo-ui

          # Full image references
          SHA_TAG=$REGISTRY/$PROJECT/$REPO/$IMAGE_NAME:${{ github.sha }}
          LATEST_TAG=$REGISTRY/$PROJECT/$REPO/$IMAGE_NAME:latest

          echo "Building $SHA_TAG"
          docker build -t $SHA_TAG .

          echo "Pushing $SHA_TAG"
          docker push $SHA_TAG

          echo "Tagging and pushing $LATEST_TAG"
          docker tag $SHA_TAG $LATEST_TAG
          docker push $LATEST_TAG
