name: Build & Push Docker Image to GCP Artifact Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install & authenticate gcloud
      - name: Setup gcloud SDK & authenticate
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      # 3. Configure Docker credential helper
      - name: Configure Docker to use gcloud
        run: |
          # the “region” part only, e.g. europe-west1
          REGION=${{ secrets.GCP_REGION }}
          # full hostname of your Artifact Registry Docker repo
          REGISTRY_HOST="$REGION-docker.pkg.dev"

          # tell docker to auth pushes/pulls against that host
          gcloud auth configure-docker $REGISTRY_HOST --quiet

      # 4. Build & push your image
      - name: Build & Push Docker Image
        run: |
          REGION="${{ secrets.GCP_REGION }}"
          PROJECT="${{ secrets.GCP_PROJECT_ID }}"
          REPO="${{ secrets.GCP_ARTIFACT_REPOSITORY }}"
          IMAGE_NAME="finovo-ui"

          HOST="$REGION-docker.pkg.dev"
          SHA_TAG="$HOST/$PROJECT/$REPO/$IMAGE_NAME:${{ github.sha }}"
          LATEST_TAG="$HOST/$PROJECT/$REPO/$IMAGE_NAME:latest"

          echo "Building image $SHA_TAG"
          docker build -t "$SHA_TAG" .

          echo "Pushing $SHA_TAG"
          docker push "$SHA_TAG"

          echo "Tagging and pushing $LATEST_TAG"
          docker tag "$SHA_TAG" "$LATEST_TAG"
          docker push "$LATEST_TAG"
