name: Build & Push Docker Image to GCP Artifact Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # define all of your secrets/consts here
    env:
      REGION: ${{ secrets.GCP_REGION }}
      PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      REPO: ${{ secrets.GCP_ARTIFACT_REPOSITORY }}
      IMAGE_NAME: finovo-ui
      HOST: ${{ secrets.GCP_REGION }}-docker.pkg.dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup gcloud SDK & authenticate
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud
        run: |
          # this will expand to e.g. "europe-west1-docker.pkg.dev"
          gcloud auth configure-docker "$HOST" --quiet

      - name: Build & Push Docker Image
        run: |
          # compute the two tags
          SHA_TAG="$HOST/$PROJECT/$REPO/$IMAGE_NAME:${GITHUB_SHA}"
          LATEST_TAG="$HOST/$PROJECT/$REPO/$IMAGE_NAME:latest"

          echo "Building image $SHA_TAG"
          docker build -t "$SHA_TAG" .

          echo "Pushing $SHA_TAG"
          docker push "$SHA_TAG"

          echo "Tagging and pushing $LATEST_TAG"
          docker tag "$SHA_TAG" "$LATEST_TAG"
          docker push "$LATEST_TAG"
